---
- name: install tomcat9 server
  hosts: localhost
  become: yes
  tasks:
    - name: install tomcat9
      ansible.builtin.apt:
        name: tomcat9
        update_cache: yes
        state: present